### PR TITLE
fix: improve error handling in UpdateForManifestWithoutSubjectToDelete

### LINKED ISSUE #459: The purge task failure and interrupted by manifest not found
**Describe the bug**
The purge task interrupted by error manifest not found

The whole error msg looks like this:

Error: failed to purge manifests: acr.BaseClient#GetManifest: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="Unknown" Message="Unknown service error" Details=[{"errors":[{"code":"MANIFEST_UNKNOWN","detail":{"Name":"msi-connector-svc.deployer.ev2","Revision":"sha256:5e4ef89a6d7f7d4c67600a2a88a637ba0379918aba710cf4df53972e5a20b3ec"},"message":"manifest sha256:5e4ef89a6d7f7d4c67600a2a88a637ba0379918aba710cf4df53972e5a20b3ec is not found"}]}]

**To Reproduce**
1. set the command: `export PURGE_CMD="acr purge --filter '.*:.*' --untagged --ago 7d --concurrency 32"`
2. create task: `az acr task create --name dailyPurgeTask --cmd "$PURGE_CMD"` ...
3. The error will happend from time to time

**Expected behavior**
Continue to the purge task for next manifest

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by ninjadq**
It should be ignored if manifest not found instead of return error and interrupt all the process

**Purpose of the PR**

- Fixes #459

### CODE REVIEW

File: cmd/common/image_functions.go [hunk 1]
```diff
@@ -247,6 +248,13 @@ func UpdateForManifestWithoutSubjectToDelete(ctx context.Context, manifest acr.M
 		var manifestBytes []byte
 		manifestBytes, err := acrClient.GetManifest(ctx, repoName, *manifest.Digest)
 		if err != nil {
+			// Check if the error is autorest.DetailedError with status code not found
+			if detailedErr, ok := err.(autorest.DetailedError); ok && detailedErr.StatusCode == http.StatusNotFound {
+				fmt.Println("Manifest", *manifest.Digest, "not found, adding to delete candidates")
+				candidatesToDelete = append(candidatesToDelete, manifest)
```
Comment (estebanreyl) [inline cmd/common/image_functions.go:254]: Why do we want to add this manifest to candidatesToDelete if it is not present? Instead, we should avoid the delete request completely

**Review by estebanreyl — CHANGES_REQUESTED** [review]
Overall looks good to me. I am currently doing tests to improve the command as a whole so will validate the changes over the next couple of days

File: cmd/common/image_functions.go (hunk 1 above)
Comment (ninjadq) [reply cmd/common/image_functions.go]: Yes, the same manifests that return 404 may appeared in multiple purge cycles. 
But add to deleteCandidate seems not work as well, I just tried delete those manifests, it still appreared in next purge. 
So it seems that we can only wait all the registries to consistent state.
Updated the PR

**Review by estebanreyl — APPROVED** [review]
LGMT
