### PR TITLE
Worker pool added to have a fixed amount of concurrent calls.

### LINKED ISSUE #7: Maximum 6 concurrent calls to the registry.
In order to not saturate the registry with http requests the go program should at most be doing 6 requests to the registry at a given time.

### PR DESCRIPTION
**Pull request by ggonzalere**
In order to not saturate the registry now only six request are done at the same time

Fixes #7

### CODE REVIEW

File: cmd/worker/worker.go [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+}
+
+// ProcessJob processes any job (currently PurgeTag and PurgeManifest)
+func (pw *PurgeWorker) ProcessJob(ctx context.Context, job PurgeJob) {
+	go func() {
+		defer pw.wg.Done()
+		switch job.JobType {
+		case PurgeTag:
+			err := api.AcrDeleteTag(ctx, job.LoginURL, job.Auth, job.RepoName, job.Tag)
+			if err != nil {
```
Comment (ehotinger) [inline cmd/worker/worker.go]: you could put a `var err error` outside of the case and then share the error logic
