### PR TITLE
Refresh of jwt tokens added

### LINKED ISSUE #35: Purge: Consider: 404 not causing errors
Maybe we could just output a warning instead for this - i.e. if something is purged regularly it may not make sense to error

### LINKED ISSUE #38: Tasks: Automatically refresh token
The token used can expired in ~60min, meaning if a Task runs longer than this (i.e. the first time someone deletes a ton of old stuff), it could fail

### PR DESCRIPTION
**Pull request by ggonzalere**
This PR adds token refreshing when using bearer authentication, also when a repository is not found or an image is not found or locked the program just prints the issue, instead of returning an error

- 

Fixes #35 
Fixes #38

### CODE REVIEW

File: cmd/api/acrsdk.go [hunk 1]
```diff
@@ -106,26 +118,82 @@ func GetAcrCLIClientWithAuth(loginURL string, username string, password string,
 
 }
 
+func RefreshAcrCLIClientToken(c *AcrCLIClient) error {
```
Comment (ehotinger) [inline cmd/api/acrsdk.go]: make private, otherwise add docs for the public function?

File: cmd/api/acrsdk.go [hunk 2]
```diff
@@ -106,26 +118,82 @@ func GetAcrCLIClientWithAuth(loginURL string, username string, password string,
...
+	ctx := context.Background()
```
Comment (ehotinger) [inline cmd/api/acrsdk.go]: pass ctx as a parameter

File: cmd/api/acrsdk.go [hunk 3]
```diff
@@ -106,26 +118,82 @@ func GetAcrCLIClientWithAuth(loginURL string, username string, password string,
...
+	c.AutorestClient.Authorizer = autorest.NewBearerAuthorizer(token)
+	exp, err := GetExpiration(token.AccessToken)
+	if err != nil {
+		return err
+	}
+	c.accessTokenExp = exp
+	return nil
+}
+
+func GetExpiration(token string) (int64, error) {
```
Comment (ehotinger) [inline cmd/api/acrsdk.go]: make private, otherwise add docs for the public function?
add unit tests?

File: cmd/api/acrsdk.go [hunk 4]
```diff
@@ -106,26 +118,82 @@ func GetAcrCLIClientWithAuth(loginURL string, username string, password string,
...
+	if err != nil {
+		return 0, err
+	}
+	if fExp, ok := mapC["exp"].(float64); ok {
+		return int64(fExp), nil
+	}
+	return 0, errors.New("unable to obtain expiration date for token")
+}
+
+func (c *AcrCLIClient) IsExpired() bool {
```
Comment (ehotinger) [inline cmd/api/acrsdk.go]: make private, otherwise add docs for the public function?

File: cmd/api/acrsdk.go [hunk 5]
```diff
@@ -49,10 +54,11 @@ func LoginURLWithPrefix(loginURL string) string {
 }
 
 func NewAcrCLIClient(loginURL string) AcrCLIClient {
-	loginURL = LoginURLWithPrefix(loginURL)
+	loginURLPrefix := LoginURLWithPrefix(loginURL)
 	return AcrCLIClient{
-		acrapi.NewWithoutDefaults(loginURL),
-		100,
+		AutorestClient:        acrapi.NewWithoutDefaults(loginURLPrefix),
+		manifestTagFetchCount: 100,
```
Comment (ehotinger) [inline cmd/api/acrsdk.go]: make a const?

Comment (ggonzalere) [reply cmd/api/acrsdk.go]: Making it a parameter makes sense, but should the error channel buffer size (for the worker) be configurable by the user?
